
<!DOCTYPE html>
<html>
<head>
  <title>Nurse Management</title>




  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">

  <!-- Include jQuery (required for DataTables) -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Include DataTables JavaScript -->
  <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>



  
  <!-- Import Google Icon Font -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <style>
    /* Custom CSS for the search field */
    .search-bar {
  display: flex;
  align-items: center;
  width: 300px;
  height: 40px;
  background-color: #f5f5f5;
  border-radius: 20px;
  overflow: hidden;
  box-shadow: 0 0px 0px rgba(47, 46, 46, 0.1);
  border: 3px solid #bbdefb; /* Set the border color */
}


    .search-bar input {
      flex: 1;
      border: none;
      outline: none;
      padding: 10px;
      font-size: 16px;
      background-color: transparent;
      text-align: center;
    }

    .search-bar button {
      border: none;
      background-color: #bbdefb;
      color: #fff;
      padding: 10px;
      border-radius: 0 20px 20px 0;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .search-bar button:hover {
      background-color: #f44211;
    }

  

    .add-button {
  background-color: #bbdefb;
  color: #ffffff;
  border-radius: 50%;
  border: 3px solid #bbdefb; 
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-left: 20px;
   /* Add some margin to separate the buttons */
}




/* Add overlay form */

.overlay {
  display: none;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.7);
  z-index: 1;
  text-align: center;
}

.form-container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: white;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}

.my-form {
  /* Form styles */
}

.close-button {
  margin-top: 10px;
  background-color: #ccc;
  border: none;
  padding: 5px 10px;
  cursor: pointer;
  border-radius: 5px;
}

.close-button:hover {
  background-color: #aaa;
}








/* Form registration styles */

.my-form {
  max-height: 600px; /* Adjust the height as needed */
  overflow-y: auto;
}

.my-form h2 {
  text-align: center;
  margin-bottom: 20px;
}

.form-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.form-row label {
  flex: 1;
  text-align: left;
  padding-right: 10px;
}

.form-row input {
  flex: 3;
}



.my-form button[type="submit"]:hover {
  background-color: #45a049;
}






/* color blue of button in table  */

.blue-button {
        background-color: lightblue;
        color: white; /* Text color is set to white for visibility */
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }











    /* Target the search input generated by DataTables */
    div.dataTables_wrapper input[type="search"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #e5e5e5;
        border-radius: 4px;
        background-color: #f5f5f5;
        color: #333;
        font-size: 14px;
        transition: border-color 0.2s, box-shadow 0.2s;
    }

    /* Style the search input when focused */
    div.dataTables_wrapper input[type="search"]:focus {
        border-color: #007bff;
        box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
    }










    /* Red Button for Delete */
.red-button {
    background-color: red;
    color: white;
    border: none;
    padding: 10px 15px;
    border-radius: 5px;
    cursor: pointer;
}

/* Green Button for Edit */
.green-button {
    background-color: green;
    color: white;
    border: none;
    padding: 10px 15px;
    border-radius: 5px;
    cursor: pointer;
}











.button-container {
  display: flex;
  justify-content: space-between;
}

.submit-button {
  background-color: green;
  color: white;
  border: none;
  padding: 20px 35px; /* Increase the padding for width and height */
  cursor: pointer;
  border-radius: 10px; /* Increase the border-radius for rounded corners */
}

.cancel-button {
  background-color: red;
  color: white;
  border: none;
  padding: 20px 35px; /* Increase the padding for width and height */
  cursor: pointer;
  border-radius: 10px; /* Increase the border-radius for rounded corners */
}










/* Radio button styling */
.radio-buttons {
  display: flex;
  align-items: center;
}

.radio-buttons label {
  display: flex;
  align-items: center;
  cursor: pointer;
  user-select: none;
  margin-right: 20px; /* Adjust the margin-right for spacing */
}

.radio-buttons label:last-child {
  margin-right: 70px; /* Remove margin-right for the last radio button */
}

.radio-buttons input[type="radio"] {
  display: none; /* Hide the actual radio input */
}

/* Style radio button when selected */
.radio-buttons input[type="radio"]:checked + span::before {
  content: '';
  display: inline-block;
  width: 12px;
  height: 12px;
  border: 2px solid green; /* Change the border color for the selected radio button */
  border-radius: 50%;
  margin-right: 5px; /* Adjust margin-right for spacing between radio and text */
}



.radio-buttons1 {
  display: flex;
  align-items: center;
}

.radio-buttons1 label {
  display: flex;
  align-items: center;
  cursor: pointer;
  user-select: none;
  margin-right: 20px; /* Adjust the margin-right for spacing */
}

.radio-buttons1 label:last-child {
  margin-right: 0px; /* Remove margin-right for the last radio button */
}

.radio-buttons1 input[type="radio"] {
  display: none; /* Hide the actual radio input */
}

/* Style radio button when selected */
.radio-buttons1 input[type="radio"]:checked + span::before {
  content: '';
  display: inline-block;
  width: 12px;
  height: 12px;
  border: 2px solid green; /* Change the border color for the selected radio button */
  border-radius: 50%;
  margin-right: 5px; /* Adjust margin-right for spacing between radio and text */
}




.nav-wrapper {
  background-color: #2196F3; /* Change to the desired background color */
  padding: 0 20px; /* Add padding to the sides if needed */
  max-width: 100%; /* Set a maximum width of 100% */
}

/* Add media queries for responsiveness */

/* You can add more media queries for other screen sizes as needed */


  </style>



</head>
<body>

  <a href="process.php"></a>

<!-- Navbar Start -->
<nav>
  <div class="nav-wrapper">

  <a href="index.html" class="brand-logo">
        <div style="max-width: 60px; max-height: 60px;">
          <img src="../img/spa.png" alt="Logo Description" style="width: 100%; height: 100%; object-fit: contain;">
        </div>
      </a>
      

    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li class="active-menu"><a href="index_in.php">Medical Records</a></li>
      <li><a href="../login.php">Log out</a></li>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><a href="about.html">Medical Records</a></li>
      <li><a href="../login.php">Log out</a></li>
</ul>

<br>
<br>



<span>
  <button id="showFormButton" class="add-button" style="display: inline;">
    <i class="fas fa-plus"></i>
  </button>
  <button onclick="resetSearch()" class="add-button" style="display: inline;">
    <i class="fas fa-file-excel"></i>
  </button>
  <button id="toggleSearchButton" class="add-button" style="display: inline;">
  <i class="fas fa-search"></i>
  </button>



</span>


 
  
<br>
<br>

<table    id="yourTableID" class="display"  >
        <thead style="background-color: #bbdefb;">
            <tr>
               <th>Date</th>
                <th>M.R record No:</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Status</th>
                <th>Address</th>
                <th>Birth Place</th>
                <th>Occupation</th>
                <th>Birthday</th>
                <th>Religion</th>
                <th>Contact No.</th>
                <th>Delete</th>
                <th>Update</th>
               
               
            </tr>
        </thead>
        <tbody>
            <?php include 'process.php'; // Include the PHP file here ?>

            <?php while ($row = $medical_record ->fetch_assoc()): ?>
                <tr>
                    <td><?= $row['date'] ?></td>
                    <td><?= $row['record_no'] ?></td>
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['age'] ?></td>
                    <td><?= $row['sex'] ?></td>
                   <td><?= $row['status'] ?></td>
                    <td><?= $row['address'] ?></td>
                    <td><?= $row['birthplace'] ?></td>
                    <td><?= $row['occupation'] ?></td>
                    <td><?= $row['birthday'] ?></td>
                    <td><?= $row['religion'] ?></td>
                    <td><?= $row['contact_no'] ?></td>
                    

                    <td>
                    <button class="red-button delete-record" data-record-id="<?= $row['id'] ?>">
    <i class="fas fa-trash"></i> Delete
</button>
</td>


<td>
    <button class="green-button" onclick="viewHistory(<?= $row['id'] ?>)">
        <i class="fas fa-edit"></i> Update
    </button>
</td>

       
      
                </tr>
            <?php endwhile; ?>
        </tbody>
    </table>











    <div id="overlay" class="overlay">
  <div id="formContainer" class="form-container">
    <form id="registrationForm" class="my-form" action="process.php" method="post">
      <h2>
        <img src="../img/header.png" alt="Registration Image" style="max-width: 100%;">
      </h2>

      <div class="form-row">
        <label for="record_no">M.R No:</label>
        <input type="text" name="record_no" required>
      </div>

      <div class="form-row">
        <label for="name">Name:</label>
        <input type="text" name="name" required>
      </div>

      <div class="form-row">
        <label for="age">Age:</label>
        <input type="text" name="age" required>
      </div>


      <div class="form-row">
  <label>Gender:</label>
  <div class="radio-buttons">
    <label>
      <input type="radio" name="sex" value="male" required>
      <span>Male</span>
    </label>
    <label>
      <input type="radio" name="sex" value="female" required>
      <span>Female</span>
    </label>
  </div>
</div>


<div class="form-row">
        <label for="address">Address:</label>
        <input type="text" name="address" required>
      </div>

      

<div class="form-row">
  <label>Status:</label>
  <div class="radio-buttons1">
    <label>
      <input type="radio" name="status" value="single" required>
      <span>Single</span>
    </label>
    <label>
      <input type="radio" name="status" value="merried" required>
      <span>Merried</span>
    </label>
    <label>
      <input type="radio" name="status" value="widow" required>
      <span>Widow</span>
    </label>
  </div>
</div>






      <div class="form-row">
        <label for="birthplace">Birthplace:</label>
        <input type="text" name="birthplace" required>
      </div>

      <div class="form-row">
        <label for="occupation">Occupation:</label>
        <input type="text" name="occupation" required>
      </div>

      <div class="form-row">
        <label for="birthday">Birthday:</label>
        <input type="text" name="birthday" required>
      </div>

      <div class="form-row">
        <label for="religion">Religion:</label>
        <input type="text" name="religion" required>
      </div>

      <div class="form-row">
        <label for="contact_no">Contact Number:</label>
        <input type="text" name="contact_no" required>
      </div>

      <!-- The existing fields remain here -->

      <button type="submit" name="submit" class="submit-button">
  <i class="fas fa-check"></i> Register
</button>
<button type="submit" id="closeFormButton" class="cancel-button">
  <i class="fas fa-times"></i> Cancel
</button>

    </form>
  </div>
</div>

















<script>





// Function to display the form when the button is clicked
document.getElementById("showFormButton").addEventListener("click", function () {
  document.getElementById("overlay").style.display = "block";
});

// Function to close the form
document.getElementById("closeFormButton").addEventListener("click", function () {
  document.getElementById("overlay").style.display = "none";
});

// Optionally, you can add more functionality to handle form submission









$(document).ready(function() {
    var table = $('#yourTableID').DataTable({
        "paging": true, // Enable pagination
        "lengthMenu": [10, 25, 50, -1], // Define the number of entries per page
        "info": true // Show entry count information
    });

    // Hide the search input initially
    $('.dataTables_filter').hide();

    $('#toggleSearchButton').on('click', function() {
        toggleSearchInput();
    });

    $('#searchButton').on('click', function() {
        performSearch(table);
    });
});

function toggleSearchInput() {
    var searchInput = $('.dataTables_filter');

    if (searchInput.is(':visible')) {
        searchInput.hide();
    } else {
        searchInput.show();
        $('#searchInput').focus();
    }
}

function performSearch(table) {
    var input = $('#searchInput').val().toLowerCase();

    // Use DataTables' built-in search
    table.search(input).draw();
}
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>
